### ISSUE TITLE
PLvsPW's .cmr2 files won't import

### ISSUE THREAD

**Issue by claire45** [Tiniifan/studio_eleven#8]
Hello. Once again, PLvsPW has a curious issue. The improvements to the XCMA importing got me to try importing once more, to sadly no good results. However, I have done a bit of testing and the .cmr2 files for other games, such as Professor Layton: Azran Legacy seem to work... or at least import? PLvsPW cameras, however, do not, returning one of two errors.
![Screenshot_5959](https://github.com/Tiniifan/Level-5-blender-addon/assets/69832485/d0f825ee-efe2-411c-8bea-f19cf05d3c29)
![Screenshot_5958](https://github.com/Tiniifan/Level-5-blender-addon/assets/69832485/03a0b846-fcae-4a9c-9abd-6ea44e422a09)

Here are the files, if you wish to take a look.
https://drive.google.com/file/d/1HrvwZkce80AknJGPkIMTK-UDZi70fb_O/view?usp=sharing

**Comment by CacaBueno64** [comment]
Hi, the addon is based on the IEGO CS/Galaxy formats, which are very different from your game.
Unfortunately we can't provide a support for theses formats, by a lack of knowledge and time.

**Comment by Tiniifan** [comment]
since we better understand the cameras, I reopen this issue

**Comment by Tiniifan** [comment]
The problem was solved in the last push, so I'm closing this issue.
